### ISSUE TITLE
Did JWTAuthenticationProvider.cs methods get implemented?

### ISSUE THREAD

**Issue by BrunoBlanes** [gavilanch/Blazor-Wasm-CRUD#1]
I was wandering if Blazor implemented [those methods](https://github.com/gavilanch/Blazor-Wasm-CRUD/blob/master/BlazorCRUDApp/Client/Auth/JWTAuthenticationProvider.cs) you mentioned for parsing the token. If they did, is there an issue on their Github? Also should this be updated? I wonder if this is still the right way to go.

**Comment by gavilanch** [comment]
Today Blazor released a new version with official support for authentication: https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-2-release-now-available/
